<?php

namespace Container4faio9S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3tD3gR0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3tD3gR0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3tD3gR0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.f4YP24X', 'get_ServiceLocator_F4YP24XService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.f4YP24X', 'get_ServiceLocator_F4YP24XService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.7pVff4h', 'get_ServiceLocator_7pVff4hService', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.Apb.We_', 'get_ServiceLocator_Apb_WeService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.J7n8Hxc', 'get_ServiceLocator_J7n8HxcService', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.eeZeAYf', 'get_ServiceLocator_EeZeAYfService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.e.uhNz.', 'get_ServiceLocator_E_UhNz_Service', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.f4YP24X', 'get_ServiceLocator_F4YP24XService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.f4YP24X', 'get_ServiceLocator_F4YP24XService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.7pVff4h', 'get_ServiceLocator_7pVff4hService', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.Apb.We_', 'get_ServiceLocator_Apb_WeService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.J7n8Hxc', 'get_ServiceLocator_J7n8HxcService', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.PYF7PhY', 'get_ServiceLocator_PYF7PhYService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.eeZeAYf', 'get_ServiceLocator_EeZeAYfService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.e.uhNz.', 'get_ServiceLocator_E_UhNz_Service', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.R0Sb2kd', 'get_ServiceLocator_R0Sb2kdService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
