<?php

namespace Container4faio9S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Apb_WeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Apb.We_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Apb.We_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'post' => ['privates', '.errored..service_locator.Apb.We_.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.Apb.We_": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
            'user' => ['privates', '.errored..service_locator.Apb.We_.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Apb.We_": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'eventDispatcher' => '?',
            'post' => 'App\\Entity\\Post',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
